language: python
python:
  - "3.4"
install:
    - pip install pytest cached-property pytest-cov
script:
    - py.test --cov=callgraph
before_install:
      - pip install codecov
after_success:
      - codecov
